spring.application.name=backend

# Servidor
server.port=8080

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/mailflow
spring.datasource.username=mailflow
spring.datasource.password=mailflow
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Seguridad — deshabilitar por ahora para poder testear con Postman
spring.security.user.name=admin
spring.security.user.password=admin