spring.application.name=backend

# Servidor
server.port=8080

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5433/mailflow?TimeZone=UTC
spring.datasource.username=mailflow
spring.datasource.password=mailflow
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Seguridad 
spring.security.user.name=admin
spring.security.user.password=admin

# JWT
jwt.secret=mailflow-secret-key-cambiar-en-produccion-debe-ser-larga
jwt.expiration=86400000